### ISSUE TITLE
Queue creation resulted in AmazonS3Exception

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AmazonSQS#164]
I got the followup at startup when the queues didn't exist yet:
```
2017-11-01 17:24:14.1650|ERROR|14|NServiceBus.Transports.SQS.QueueCreator|Exception from CreateQueueIfNecessary.
Amazon.S3.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
```

Here is the log file, it seems to indicate that there is some sort of race condition happening within this single endpoints:

[trace.log](https://github.com/Particular/NServiceBus.AmazonSQS/files/1435063/trace.log)

**Comment by danielmarbach** [comment]
@ramonsmits any ideas why you got so many NotFound exceptions in between?

**Comment by ramonsmits** [comment]
The Not Found exceptions are logged via the AppDomain FirstChangeException, those seem to be handled by the SDK. Not sure what those are about.
```
2017-11-01 17:24:13.4078|DEBUG|14|FirstChanceException|The remote server returned an error: (404) Not Found.
Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 230
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 251
```

**Comment by danielmarbach** [comment]
I'm not sure what the value of logging first chance exception is in the perf test suite. I tripped over this once as well until I realized that these are expected exceptions happening behind the scenes. Why would be want to see those? what value would we derive from it?
