### ISSUE TITLE
On the wire compatibility- subscriptions v5 - v7 fails on ReplyToAddress header

### ISSUE THREAD

**Issue by seanfarmar** [Particular/NServiceBus.AmazonSQS#232]
A customer has this issue:

I have an endpoint running NSBv5 and another, running version 7.

The NSBv5 sends the following subscription message:

```{  
   "Headers":{  
      "NServiceBus.MessageId":"ba4bfdc7-8d42-48ae-8664-a90e010daac9",
      "NServiceBus.CorrelationId":"ba4bfdc7-8d42-48ae-8664-a90e010daac9",
      "NServiceBus.MessageIntent":"Subscribe",
      "NServiceBus.Version":"5.2.25",
      "NServiceBus.TimeSent":"2018-06-29 15:21:49:678261 Z",
      "NServiceBus.ControlMessage":"True",
      "SubscriptionMessageType":"GRM.Rights.Events.DealContractualLanguageDealMessagePublished, GRM.Rights.Events, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
   },
   "TimeToBeReceived":"10675199.02:48:05.4775807",
   "Body":"empty message",
   "S3BodyKey":null,
   "ReplyToAddress":{  
      "Queue":"GRM.Rights.ServiceBus.Core",
      "Machine":"UKHAMWL93730"
   }
}
```

 

The NSBv7 endpoint fails to handle the message:  (I do set  transport.EnableV1CompatibilityMode() in NSB7 endpoint)

 
```
2018-06-29 16:03:56,343 [8] WARN NServiceBus.Transports.SQS.MessagePump [(null)] - Treating message with SQS Message Id 8869dadb-a5e3-4722-a14c-7fd30858d4cc as a poison message due to exception Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'ReplyToAddress', line 1, position 573.
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
at Newtonsoft.Json.JsonTextReader.ReadAsString()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at NServiceBus.Transports.SQS.MessagePump.<ProcessMessage>d__7.MoveNext(). Moving to error queue.
```

**Comment by boblangley** [comment]
Fixed in https://github.com/Particular/NServiceBus.AmazonSQS/commit/d63385102dc9db571615380b05ad645e399cace0
