### ISSUE TITLE
`DoNotWrapOutgoingMessages` set to true cannot be used with NServiceBus.Metrics.ServiceControl

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.AmazonSQS#2520]
#### Description

Setting [DoNotWrapOutgoingMessages](https://docs.particular.net/transports/sqs/configuration-options#do-not-wrap-message-payload-in-a-transport-envelope) to `true` causes [the performance monitoring ServiceControl plugin](https://docs.particular.net/monitoring/metrics/install-plugin) to log exceptions when sending raw data monitoring reports. 

#### Expected behavior

This configuration should work without a problem.

#### Actual behavior

Endpoints that use the SQS transport and try to send performance monitoring reports to ServiceControl, log the errors similar to:

``` code
Amazon.SQS.Model.InvalidMessageContentsException: Invalid binary character '#x1' was found in the message body, the set of allowed characters is #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF].
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at NServiceBus.Transport.SQS.MessageDispatcher.SendMessage(SqsPreparedMessage message, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SQS/MessageDispatcher.cs:line 336
   at NServiceBus.Transport.SQS.MessageDispatcher.SendMessageForBatch(SqsPreparedMessage message, Int32 batchNumber, Int32 totalBatches, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SQS/MessageDispatcher.cs:line 328
   at NServiceBus.Transport.SQS.MessageDispatcher.SendBatch(SqsBatchEntry batch, Int32 batchNumber, Int32 totalBatches, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SQS/MessageDispatcher.cs:line 202
   at NServiceBus.Transport.SQS.MessageDispatcher.DispatchBatched(IEnumerable`1 toBeBatchedTransportOperations, Dictionary`2 multicastEventsMessageIdsToType, TransportTransaction transportTransaction, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SQS/MessageDispatcher.cs:line 168
   at NServiceBus.Transport.SQS.MessageDispatcher.Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SQS/MessageDispatcher.cs:line 92
   at NServiceBus.Metrics.ServiceControl.ReportingFeature.ServiceControlRawDataReporting.<>c__DisplayClass3_0.<<CreateReporter>g__Sender|0>d.MoveNext() in C:\git\p\NServiceBus.Metrics.ServiceControl\src\NServiceBus.Metrics.ServiceControl\ReportingFeature.cs:line 282
``` 

#### Versions
Likely all transports that support the `DoNotWrapOutgoingMessages` option ie.
- 5.x
- 6.x
- 7.x

### Steps to reproduce

Setup an endpoint that processes some messages and
* is using `Particular.Metrics.ServiceControl`
* has `DoNotWrapOutgoingMessages` transport options set to `true`

#### Workarounds

Turn off the `DoNotWrapOutgoingMessages` option.

**Comment by mikesigs** [comment]
Hi folks. I'm still struggling through this SQS migration. It looks like there's another issue detecting message size and properly using the large message support via S3. In speaking with @lailabougria, she is recommending I try using the `DoNotWrapOutgoingMessages` feature, but then this issue is still open so that is not an option. Any chance you could devote some resource to fixing this issue? Please and thank you of course!

**Comment by mauroservienti** [comment]
@mikesigs we raised #2623 to spike one way to address this issue. We still have a couple of rough edges to smooth, but it looks promising.

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus.AmazonSQS/pull/2646
